baseURL = "/"
languageCode = "en-us"
title = "nsfw"
theme = "zem"
# enable emoji 😍
enableEmoji = true
# footnotes return link
footnoteReturnLinkContents = "↩"
footnoteAnchorPrefix = "fn"
# chuyển list title về số ít (bỏ s)
pluralizeListTitles = false
# remove accent mark
# dấu-tiếng-việt to dau-tieng-viet
removePathAccents = true
# posts per page
paginate = 6

# built-in code highlight settings
# pygmentsCodefences = true
# pygmentsUseClasses = true
# pygmentsOptions = "linenos=table"

# [outputs]
#   home = ["HTML","RSS","JSON"]

[params]
  author = "khongdangky"
  description = "this is my only blog, I have never write and post anywhere else"
  tagline = "everything not art must be porn"
  googlefont = "https://fonts.googleapis.com/css?family=IBM+Plex+Mono:400,400i,600,600i&display=swap&subset=latin-ext,vietnamese"
  mpPrimary = "content-primary" # mount point for primary content
  mpSecondary = "content-secondary" # mount point for secondary content
  bigCover = "1200x680" # image size for big cover image (home and single page)
  smallCover = "640x640" # image size for small post cover image (post listing)

# uncomment below line to enable tracking post date with git
# enableGitInfo = true
# replace below line in [frontmatter]
# lastmod = [":fileModTime", ":git", ":default"]
[frontmatter]
  date  = [":default", ":filename"]
  lastmod = [":fileModTime", ":default"]

# edit this for your own post permalinks
[permalinks]
  content-primary = "blog/:year/:month/:slug/"
  content-secondary = "collective/:slug/"


# home page menu
[[menu.home]]
  name = "home"
  weight = 1
  url = "/"

# pages (section) menu
[[menu.main]]
  name = "home"
  weight = 1
  url = "/"
[[menu.main]]
  name = "tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

# footer menu
[[menu.footer]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.footer]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.footer]]
  name = "Emoji"
  weight = 40
  identifier = "emoticon"
  url = "https://www.webfx.com/tools/emoji-cheat-sheet/"

# relate posts
[related]
threshold = 80.0
includeNewer = true
toLower = false

  [[related.indices]]
  name = "categories"
  weight = 100.0

  [[related.indices]]
  name = "tags"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0

# setting to render sitemap
# not very important
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# settings for image processing
[imaging]
# Better but slower resize quality
resampleFilter = "lanczos"
# Better JPEG quality setting. Default is 75.
quality = 85
# Default jpg image background if it render from transparent images.
bgColor = "#ffffff"

# Use hugo module to mount content from local folder
# Change below source to your content path (relate to your hugo folder)
# you can even use your github/gitlab repositories
[module]
[[module.mounts]]
source = "../content/kele"
target = "content/content-primary"
[[module.mounts]]
source = "../content/nhatnhanh"
target = "content/content-secondary"

